/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Bussines.LoadDatas;
import Data.Alarm;
import Data.Event;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Ivan Solano
 */
public class CrearAlarma extends javax.swing.JFrame {

    /**
     * Creates new form CrearAlarma
     */
    private Event event;
    private ArrayList<Alarm> listAlarms;
    private Alarm alarm;
    private ArrayList<Event> listEvents;
    private Date date;
    private String tipoAlarm;
    private int posicion;
    private String uxTime;
    private String[] time;
    private boolean valFecha;
    
    static Event defaultEvent;
    static boolean isFromCreateEvent;
    static boolean isFromEditEvent;
    static Alarm defaultAlarm;
    
    public CrearAlarma() {
        initComponents();
        event=new Event();
        alarm=null;
        valFecha=true;
        defaultEvent = new Event();
        listEvents=new ArrayList();
        listAlarms=new ArrayList();
        isFromCreateEvent=false;
        isFromEditEvent=false;
        defaultAlarm= new Alarm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Alarma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setText("Fecha:");

        jLabel2.setText("Tipo de Alerta: ");

        jLabel3.setText("Hora: ");

        jCheckBox1.setText("Sonido");

        jCheckBox2.setText("Correo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
       
//                uxTime=(String)jSpinner1.getValue();
//                time=uxTime.split(":");

                
                
                
                
       event=defaultEvent;
       listEvents=LoadDatas.readEvents();
       
        System.out.println(event);
       if(!isFromEditEvent)
       {
           validDatas();
       }
       if(valFecha&&!isFromEditEvent){
           loadDatas();
       }
 
        if(!valFecha&&!isFromEditEvent) 
        {
            valFecha=true;
            JOptionPane.showMessageDialog(this,"Elija una fecha coherente");
     

        }
        else if(!isFromCreateEvent&&!isFromEditEvent)
        {
            System.out.println("!isFromCreateEvent&&!isFromEditEvent");
            fromCreateAlarm();
   
        }
        else if(isFromCreateEvent)
        {   System.out.println("isFromCreateEvent"); 
            // No se guarda que no se repita el objeto dos veces.
            defaultEvent=event;
            isFromCreateEvent=false;
            this.setVisible(false);
            
        }
        else
        {
            System.out.println("isFromEditEvent");
            fromEditEvent();
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    public void fromEditEvent()
    {
       try
        {
            date=jDateChooser1.getDate();
                if(jComboBox3.getSelectedItem().toString().equals("PM")){
                    int hora = Integer.parseInt(jComboBox1.getSelectedItem().toString());
                    int horamilitar=hora +12;
                    int minutos =Integer.parseInt(jComboBox2.getSelectedItem().toString());
                    date.setHours(horamilitar);
                    date.setMinutes(minutos);
                    date.setSeconds(00);
                }if(jComboBox3.getSelectedItem().toString().equals("AM")){
                    int hora= Integer.parseInt(jComboBox1.getSelectedItem().toString());
                    int minutos =Integer.parseInt(jComboBox2.getSelectedItem().toString());
                    date.setHours(hora);
                    date.setMinutes(minutos);
                    date.setSeconds(00);
                }
        
            if(date.compareTo(new Date())!=-1)
            {
                loadDatas();
                this.setVisible(false);
                isFromEditEvent=false;
            }else
            {
                JOptionPane.showMessageDialog(this,"Sea coherente con los datos");
            }
            
        }catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(this,"Sea coherente con los datos");
        }
        
    }
    
    public void validDatas()
    {
       try
       {
           date=jDateChooser1.getDate();
                if(jComboBox3.getSelectedItem().toString().equals("PM")){
                    int hora = Integer.parseInt(jComboBox1.getSelectedItem().toString());
                    int horamilitar=hora +12;
                    int minutos =Integer.parseInt(jComboBox2.getSelectedItem().toString());
                    date.setHours(horamilitar);
                    date.setMinutes(minutos);
                    date.setSeconds(00);
                }if(jComboBox3.getSelectedItem().toString().equals("AM")){
                    int hora= Integer.parseInt(jComboBox1.getSelectedItem().toString());
                    int minutos =Integer.parseInt(jComboBox2.getSelectedItem().toString());
                    date.setHours(hora);
                    date.setMinutes(minutos);
                    date.setSeconds(00);
                }
           
           if(date.compareTo(new Date())==-1) valFecha=false;
 
           
       }catch(NullPointerException e)
       {
           valFecha=false;
       }
       try
       {
            for (int i = 0; i <LoadDatas.readEvents().size(); i++) {
                if(listEvents.get(i).getName().equals(event.getName())&&listEvents.get(i).getDate()
                        .equals(event.getDate())&&listEvents.get(i).getPlace().equals(event.getPlace())){
                    posicion=i;
                   listEvents.remove(i);
                    
                } 
            }
 
        }
        catch(IndexOutOfBoundsException e)
        {
            System.out.println("error linea 246 Alarm");
        }catch(NullPointerException e)
        {
            System.out.println("error linea 246 Alarm no tiene alarmas");
        }
    }
    
    public void loadDatas()
    {
    
        if(jCheckBox1.isSelected()&&jCheckBox2.isSelected())
            {
                    tipoAlarm=jCheckBox1.getLabel()+","+jCheckBox2.getLabel();
            }
            else if(jCheckBox1.isSelected())
            {
                    tipoAlarm=jCheckBox1.getLabel();
            }
            else tipoAlarm=jCheckBox2.getLabel();
            alarm= new Alarm(tipoAlarm,date);
            listAlarms=event.getAlarm(); 
            listAlarms.add(alarm);
            event.setAlarm(listAlarms);
            listEvents.add(posicion, event);
    }
    
     private void fromCreateAlarm()
    {    
      LoadDatas.saveEvents(listEvents);
      this.setVisible(false);
    }
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearAlarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearAlarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearAlarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearAlarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearAlarma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}